version: '3.7'

services:
  brew_auth:
    build: ./brew_auth_service/app
    volumes:
      - ./brew_auth_service/app/:/usr/src/app/
    environment: 
      - HOST=0.0.0.0
      - PORT=8001
    ports:
      - 8001:8001
    env_file:
      - ./brew_auth_service/.env.dev
    depends_on:
        - db
    networks:
      - brew

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev
    networks:
      - brew

  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - brew_auth
    networks:
      - brew

volumes:
  postgres_data:

networks:
  brew:
    driver: bridge
    ipam:
      config:
        - subnet: 10.1.1.0/24