version: '3.7'

services:
  brew_auth:
    build: ./brew_auth_service/app
    volumes:
      - ./brew_auth_service/app/:/usr/src/app/
      - static_volume:/usr/src/app/staticfiles
    environment:
      - HOST=0.0.0.0
      - PORT=8001
    ports:
      - 8001:8001
    env_file:
      - ./brew_auth_service/.env.dev
    depends_on:
      - db
    networks:
      - brew

  brew_warehouse:
    build: ./brew_warehouse_service/app
    volumes:
      - ./brew_warehouse_service/app/:/usr/src/app/
      - static_volume:/usr/src/app/staticfiles
    environment:
      - HOST=0.0.0.0
      - PORT=8002
    ports:
      - 8002:8002
    env_file:
      - ./brew_warehouse_service/.env.dev
    depends_on:
      - db
      - brew_auth
    networks:
      - brew

  brew_sales:
    build: ./brew_sales_service/app
    volumes:
      - ./brew_sales_service/app/:/usr/src/app/
      - static_volume:/usr/src/app/staticfiles
    environment:
      - HOST=0.0.0.0
      - PORT=8003
    ports:
      - 8003:8003
    env_file:
      - ./brew_sales_service/.env.dev
    depends_on:
      - db
      - brew_auth
    networks:
      - brew

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    networks:
      - brew

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/usr/src/app/staticfiles
    ports:
      - 80:80
    depends_on:
      - brew_auth
      - brew_warehouse
      - brew_sales
    networks:
      - brew

volumes:
  postgres_data:
  static_volume:

networks:
  brew:
    driver: bridge
    ipam:
      config:
        - subnet: 10.1.1.0/24